In [1]:
import os

In [2]:
os.chdir('F:/Analytics Vidya/Loan Prediction')

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [5]:
train.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
test.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [7]:
x=train.iloc[:,1:12]
y=train.iloc[:,[12]]
test=test.iloc[:,1:]

In [8]:
test.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male     Yes          0      Graduate            No             5720   
1   Male     Yes          1      Graduate            No             3076   
2   Male     Yes          2      Graduate            No             5000   
3   Male     Yes          2      Graduate            No             2340   
4   Male      No          0  Not Graduate            No             3276   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0       110.0             360.0             1.0   
1               1500       126.0             360.0             1.0   
2               1800       208.0             360.0             1.0   
3               2546       100.0             360.0             NaN   
4                  0        78.0             360.0             1.0   

  Property_Area  
0         Urban  
1         Urban  
2         Urban  
3         Urban  
4         Urban

In [9]:
x.Gender=x['Gender'].fillna('Male')
x.Dependents=x['Dependents'].fillna('0')
x.Married=x['Married'].fillna('Yes')
x.Self_Employed=x['Self_Employed'].fillna('No')
test.Gender=x['Gender'].fillna('Male')
test.Dependents=x['Dependents'].fillna('0')
test.Self_Employed=x['Self_Employed'].fillna('No')


In [10]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [11]:
x.Gender=encoder.fit_transform(x.Gender)
x.Dependents=encoder.fit_transform(x.Dependents)
x.Married=encoder.fit_transform(x.Married)
x.Self_Employed=encoder.fit_transform(x.Self_Employed)
x.Education=encoder.fit_transform(x.Education)
x.Property_Area=encoder.fit_transform(x.Property_Area)
test.Gender=encoder.fit_transform(test.Gender)
test.Dependents=encoder.fit_transform(test.Dependents)
test.Married=encoder.fit_transform(test.Married)
test.Self_Employed=encoder.fit_transform(test.Self_Employed)
test.Education=encoder.fit_transform(test.Education)
test.Property_Area=encoder.fit_transform(test.Property_Area)



In [12]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [13]:
imp=IterativeImputer()

In [14]:
x1=imp.fit_transform(x)
test1=imp.fit_transform(test)
x1=pd.DataFrame(x1,columns=x.columns)
test1=pd.DataFrame(test1,columns=test.columns)

Train test split

In [15]:
from sklearn.model_selection import train_test_split

In [58]:
x_train,x_test,y_train,y_test=train_test_split(x1,y,test_size=0.2,random_state=0)

Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression


In [20]:
logis = LogisticRegression(random_state=0)


In [59]:
logis.fit(x_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

predict on test data

In [60]:
y_pred=logis.predict(x_test)

In [61]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[15, 18],
       [ 2, 88]], dtype=int64)

In [62]:
from sklearn.metrics import precision_recall_fscore_support,accuracy_score,f1_score
accuracy_score(y_test,y_pred)


0.8373983739837398

In [63]:
f1_score(encoder.fit_transform(y_test),encoder.fit_transform(y_pred))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


0.8979591836734695

In [64]:
from sklearn.metrics import roc_auc_score

In [65]:
roc_auc_score(encoder.fit_transform(y_test),encoder.fit_transform(y_pred))

0.7161616161616162

Decision tree 

In [42]:
from sklearn.tree import DecisionTreeClassifier

In [43]:
decision=DecisionTreeClassifier()

In [66]:
decision.fit(x_train,y_train)

DecisionTreeClassifier()

In [67]:
y_pred_dec=decision.predict(x_test)

In [68]:
cm_dec=confusion_matrix(y_test,y_pred_dec)

In [69]:
cm_dec

array([[20, 13],
       [26, 64]], dtype=int64)

In [70]:
f1_score(encoder.fit_transform(y_test),encoder.fit_transform(y_pred_dec))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


0.7664670658682636

In [71]:
roc_auc_score(encoder.fit_transform(y_test),encoder.fit_transform(y_pred_dec))

0.6585858585858586

Random Forest

In [50]:
from sklearn.ensemble import RandomForestClassifier

In [79]:
rf=RandomForestClassifier(n_estimators=500)

In [80]:
rf.fit(x_train,y_train)

<ipython-input-80-895403b03771>:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(x_train,y_train)


RandomForestClassifier(n_estimators=500)

In [81]:
y_pred_rf=rf.predict(x_test)

In [82]:
cm_rf=confusion_matrix(y_test,y_pred_rf)

In [83]:
cm

array([[15, 18],
       [ 2, 88]], dtype=int64)

In [85]:
f1_score(encoder.fit_transform(y_test),encoder.fit_transform(y_pred_rf))

0.869109947643979

In [86]:
roc_auc_score(encoder.fit_transform(y_test),encoder.fit_transform(y_pred_rf))

0.6883838383838384

prediction on test

In [90]:
test=pd.DataFrame(logis.predict(test1))

In [91]:
test.to_csv('F:\Analytics Vidya\Loan Prediction\SampleSubmission.csv')